apiVersion: v1
kind: Namespace
metadata:
  name: ai-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: 100.84.115.22:30080/library/ai-agent:v0.1 # use local harbor image repo.
        ports:
        - containerPort: 5000 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent-ui
  namespace: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent-ui
  template:
    metadata:
      labels:
        app: ai-agent-ui
    spec:
      containers:
      - name: web-server
        image: 100.84.115.22:30080/library/ai-agent-ui:v0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: ai-agent
spec:
  type: NodePort
  selector:
    app: ai-agent
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30123
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-ui
  namespace: ai-agent
spec:
  type: NodePort
  selector:
    app: ai-agent-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30321